In [112]:
import torch

In [113]:
x = torch.rand(1)
b = torch.rand(1,requires_grad=True)
w = torch.rand(1,requires_grad=True)
y = w * x
z = y + b

In [114]:
x.requires_grad,b.requires_grad,w.requires_grad,y.requires_grad,z.requires_grad

(False, True, True, True, True)

In [115]:
x.is_leaf,w.is_leaf,y.is_leaf,z.is_leaf,b.is_leaf #判断是否是叶子节点

(True, True, False, False, True)

In [116]:
# 反向传播计算
z.backward(retain_graph=True) # 如果不清空会累加起来

In [117]:
w.grad,b.grad

(tensor([0.5380]), tensor([1.]))

In [118]:
import numpy as np

In [119]:
# 线性回归
x_values = [i for i in range(11)]
x_train = np.array(x_values,dtype=np.float32) 
x_train = x_train.reshape(-1,1) # norm
x_train.shape

(11, 1)

In [120]:
y_values = [2*i for i in range(11)]
y_train = np.array(y_values,dtype=np.float32)
y_train = y_train.reshape(-1,1)
y_train.shape

(11, 1)

In [121]:
x_train,y_train

(array([[ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]], dtype=float32), array([[ 0.],
        [ 2.],
        [ 4.],
        [ 6.],
        [ 8.],
        [10.],
        [12.],
        [14.],
        [16.],
        [18.],
        [20.]], dtype=float32))

In [122]:
import torch
import torch.nn as nn

In [123]:
class LinearRegressionModel(nn.Module):

  def __init__(self,input_dim,output_dim):
    super(LinearRegressionModel,self).__init__()
    self.linear = nn.Linear(input_dim,output_dim)

  def forward(self,x):
    out = self.linear(x)
    return out

In [124]:
input_dim = 1
output_dim = 1
model = LinearRegressionModel(input_dim,output_dim) #create model

In [125]:
model

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

In [126]:
epoches = 0 # iterator 1000
lr = 0.001
optimizer = torch.optim.Adam(model.parameters(),lr=lr)
criterion = nn.MSELoss()

In [127]:
while True:
  epoches+=1
  inputs = torch.from_numpy(x_train)
  labels = torch.from_numpy(y_train)
  optimizer.zero_grad() # clean grad

  out = model(inputs)

  # get loss function
  loss = criterion(out,labels)
  loss.backward()

  # update weights
  optimizer.step()
  if epoches % 100 == 0:
    print('epoch {}, loss {}'.format(epoches, loss.item()))
  if epoches > 10000:
    break

epoch 100, loss 104.87847137451172
epoch 200, loss 91.9978256225586
epoch 300, loss 80.34309387207031
epoch 400, loss 69.83487701416016
epoch 500, loss 60.396793365478516
epoch 600, loss 51.955257415771484
epoch 700, loss 44.43929672241211
epoch 800, loss 37.780357360839844
epoch 900, loss 31.912353515625
epoch 1000, loss 26.77142333984375
epoch 1100, loss 22.29595947265625
epoch 1200, loss 18.426599502563477
epoch 1300, loss 15.10617733001709
epoch 1400, loss 12.279837608337402
epoch 1500, loss 9.895108222961426
epoch 1600, loss 7.902050495147705
epoch 1700, loss 6.253365993499756
epoch 1800, loss 4.904572010040283
epoch 1900, loss 3.814194440841675
epoch 2000, loss 2.9438958168029785
epoch 2100, loss 2.2586803436279297
epoch 2200, loss 1.7269248962402344
epoch 2300, loss 1.3205184936523438
epoch 2400, loss 1.014818787574768
epoch 2500, loss 0.7886104583740234
epoch 2600, loss 0.62396240234375
epoch 2700, loss 0.506018877029419
epoch 2800, loss 0.422750860452652
epoch 2900, loss 0.364

In [137]:
data = np.array([[1,2,3,4,5,6,7,8,9,0]],dtype=np.float32)
print(data.shape)
data = data.reshape(-1,1)
print(data.shape)
predicted = model(torch.from_numpy(data))
print(predicted)

(1, 10)
(10, 1)
tensor([[2.0009e+00],
        [4.0008e+00],
        [6.0006e+00],
        [8.0004e+00],
        [1.0000e+01],
        [1.2000e+01],
        [1.4000e+01],
        [1.6000e+01],
        [1.8000e+01],
        [1.1074e-03]], grad_fn=<AddmmBackward>)


In [130]:
data

array([[1.]], dtype=float32)