In [1]:
import torch
import numpy as np

In [3]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [4]:
arr2 = arr.reshape(2,3)
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
data = torch.from_numpy(arr2)
data

tensor([[0, 1, 2],
        [3, 4, 5]])

In [6]:
data.shape

torch.Size([2, 3])

In [9]:
data.squeeze(1),data.squeeze(1).shape

(tensor([[0, 1, 2],
         [3, 4, 5]]), torch.Size([2, 3]))

In [10]:
data.squeeze(0),data.squeeze(0).shape

(tensor([[0, 1, 2],
         [3, 4, 5]]), torch.Size([2, 3]))

unsqueeze 代表的是增加一个维度

In [11]:
data.unsqueeze(0),data.unsqueeze(0).shape

(tensor([[[0, 1, 2],
          [3, 4, 5]]]), torch.Size([1, 2, 3]))

In [12]:
data.unsqueeze(1),data.unsqueeze(1).shape

(tensor([[[0, 1, 2]],
 
         [[3, 4, 5]]]), torch.Size([2, 1, 3]))

In [13]:
data.unsqueeze(2),data.unsqueeze(2).shape

(tensor([[[0],
          [1],
          [2]],
 
         [[3],
          [4],
          [5]]]), torch.Size([2, 3, 1]))

squeeze代表去除一个维度,但是该维度必须要是1,而不能大于0

In [15]:
data.unsqueeze(2).squeeze(2),data.unsqueeze(2).squeeze(2).shape

(tensor([[0, 1, 2],
         [3, 4, 5]]), torch.Size([2, 3]))